# SPDX-License-Identifier: Apache-2.0
---
- name: Add the repository registration handlers
  ansible.builtin.import_tasks: repository.yml

- name: Add the package installation handlers
  ansible.builtin.import_tasks: install.yml
