# SPDX-License-Identifier: Apache-2.0
---
- name: Ensure netplan is installed
  ansible.builtin.apt:
    name:
      - netplan.io
    state: present

- name: Remove existing configuration
  ansible.builtin.file:
    path: "/etc/netplan/{{ item }}"
    state: absent
  loop:
    - 00-snapd-config.yaml
    - 00-installer-config.yaml
    - 10-lxc.yaml
    - 50-cloud-init.yaml
  notify: Apply netplan

- name: Transfer netplan configuration
  ansible.builtin.copy:
    src: "{{ netplan_config_dir }}/{{ inventory_hostname }}.yaml"
    dest: /etc/netplan/00-ansible-main.yaml
    mode: "0600"
  notify: Apply netplan

- name: Apply netplan
  ansible.builtin.command: netplan apply
  changed_when: true
