---

- name: Netplan role
  hosts: all
  order: shuffle
  gather_facts: yes
  gather_subset:
    - "distribution_release"
  roles:
    - netplan

- name: Environment role
  hosts: all
  order: shuffle
  gather_facts: yes
  gather_subset:
    - "distribution_release"
  roles:
    - environment

- name: NVMe role
  hosts: all
  order: shuffle
  gather_facts: yes
  gather_subset:
    - "distribution_release"
  roles:
    - nvme

- name: Ceph role
  hosts: all
  order: shuffle
  gather_facts: yes
  gather_subset:
    - "distribution_release"
    - "default_ipv4"
    - "default_ipv6"

  roles:
    - ceph
    
- name: LVM Cluster role
  hosts: all
  order: shuffle
  gather_facts: yes
  gather_subset:
    - "distribution_release"
    - "default_ipv4"
    - "default_ipv6"
  roles:
    - lvmcluster

- name: OVN role
  hosts: all
  order: shuffle
  gather_facts: yes
  gather_subset:
    - "distribution_release"
    - "default_ipv4"
    - "default_ipv6"
  roles:
    - ovn

- name: Incus role
  hosts: all
  order: shuffle
  gather_facts: yes
  gather_subset:
    - "distribution_release"
    - "default_ipv4"
    - "default_ipv6"

  roles:
    - incus
