- name: Create cluster directory
  delegate_to: 127.0.0.1
  ansible.builtin.file:
    path: "{{ lvmcluster_config_dir }}/{{ lvmcluster_name }}"
    mode: "0755"
    state: directory
  throttle: 1
  when: 'lvmcluster_name is defined'
  notify: Create cluster host_id tracking
