- name: Create cluster directory
  delegate_to: 127.0.0.1
  ansible.builtin.file:
    path: "{{ lvmcluster_config_dir }}/{{ lvmcluster_name }}"
    mode: "0755"
    state: directory
  throttle: 1
  when: 'lvmcluster_name'
  register: create

- name: Create cluster host_id tracking
  delegate_to: 127.0.0.1
  throttle: 1
  ansible.builtin.copy:
    content: "{}"
    dest: "{{ lvmcluster_config_dir }}/{{ lvmcluster_name }}/host_id.yaml"
    mode: "0644"
  tags:
    - skip_ansible_lint
  when: "create.changed"

- name: Update cluster host_id tracking
  delegate_to: 127.0.0.1
  throttle: 1
  ansible.builtin.template:
    src: host_id.yaml.j2
    dest: "{{ lvmcluster_config_dir }}/{{ lvmcluster_name }}/host_id.yaml"
    mode: "0644"
  when: 'lvmcluster_name'
  vars:
    lvmcluster_host_ids: "{{ lookup('file', lvmcluster_config_dir + '/' + lvmcluster_name + '/host_id.yaml') | from_yaml }}"
