---
- name: Bootstrap Ceph mon
  shell:
    cmd: sudo -u ceph ceph-mon --mkfs -i {{ inventory_hostname_short }} --monmap /var/lib/ceph/bootstrap-mon/ceph.monmap --keyring /var/lib/ceph/bootstrap-mon/ceph.keyring
    creates: /var/lib/ceph/mon/ceph-{{ inventory_hostname_short }}/keyring
  notify:
    - Enable msgr2
    - Disable insecure_global_id_reclaim

- name: Enable and start Ceph mon
  systemd:
    enabled: yes
    name: ceph-mon@{{ inventory_hostname_short }}
    state: started

- name: Run all notified handlers
  meta: flush_handlers
