# SPDX-License-Identifier: Apache-2.0
---
- name: Transfer the cluster configuration
  ansible.builtin.template:
    src: ceph.conf.j2
    dest: /etc/ceph/ceph.conf
    mode: "0644"
  notify: Restart Ceph
  when: 'ceph_roles|length > 0'

- name: Create main storage directory
  ansible.builtin.file:
    path: /var/lib/ceph
    owner: ceph
    group: ceph
    mode: "0750"
    state: directory
  when: 'ceph_roles|length > 0 and (ceph_roles|length > 1 or ceph_roles[0] != "client")'

- name: Create monitor bootstrap path
  ansible.builtin.file:
    path: /var/lib/ceph/bootstrap-mon
    owner: ceph
    group: ceph
    mode: "0770"
    state: directory
  when: '"mon" in ceph_roles'

- name: Create OSD bootstrap path
  ansible.builtin.file:
    path: /var/lib/ceph/bootstrap-osd
    owner: ceph
    group: ceph
    mode: "0770"
    state: directory
  when: '"osd" in ceph_roles'

- name: Transfer main admin keyring
  ansible.builtin.copy:
    src: '{{ ceph_client_admin_keyring }}'
    dest: /etc/ceph/ceph.client.admin.keyring
    owner: ceph
    group: ceph
    mode: "0660"
  notify: Restart Ceph
  when: '("client" in ceph_roles and "admin" in ceph_keyrings) or "mon" in ceph_roles'

- name: Transfer additional client keyrings
  ansible.builtin.copy:
    src: '{{ ceph_config_dir }}/cluster.{{ ceph_fsid }}.client.{{ item }}.keyring'
    dest: '/etc/ceph/ceph.client.{{ item }}.keyring'
    owner: ceph
    group: ceph
    mode: "0660"
  with_items:
    '{{ ceph_keyrings | difference(["admin"]) }}'
  when: '"client" in ceph_roles'

- name: Transfer bootstrap mon keyring
  ansible.builtin.copy:
    src: '{{ ceph_mon_keyring }}'
    dest: /var/lib/ceph/bootstrap-mon/ceph.keyring
    owner: ceph
    group: ceph
    mode: "0660"
  when: '"mon" in ceph_roles'

- name: Transfer bootstrap mon map
  ansible.builtin.copy:
    src: '{{ ceph_mon_map }}'
    dest: /var/lib/ceph/bootstrap-mon/ceph.monmap
    owner: ceph
    group: ceph
    mode: "0660"
  when: '"mon" in ceph_roles'

- name: Transfer bootstrap OSD keyring
  ansible.builtin.copy:
    src: '{{ ceph_bootstrap_osd_keyring }}'
    dest: /var/lib/ceph/bootstrap-osd/ceph.keyring
    owner: ceph
    group: ceph
    mode: "0660"
  when: '"osd" in ceph_roles'
