---

- name: Create /var/lib/ceph/mds/ceph-{{ inventory_hostname_short }}
  file:
    path: /var/lib/ceph/mds/ceph-{{ inventory_hostname_short }}
    owner: ceph
    group: ceph
    mode: 0770
    state: directory
  register: deploy_mds
  when: '"mds" in ceph_roles'

- name: Create mds keyring
  delegate_to: "{{ lookup('template', 'ceph.monitors.names.j2') | from_yaml | first }}"
  shell:
    cmd: ceph auth get-or-create mds.{{ inventory_hostname_short }} mon 'profile mds' mgr 'profile mds' mds 'allow *' osd 'allow *'
  register: mds_keyring
  when: '"mds" in ceph_roles and deploy_mds.changed'

- name: Transfer mds keyring
  copy:
    content: "{{ mds_keyring.stdout }}\n"
    dest: "/var/lib/ceph/mds/ceph-{{ inventory_hostname_short }}/keyring"
    owner: ceph
    group: ceph
    mode: 0660
  when: '"mds" in ceph_roles and deploy_mds.changed'

- name: Enable ceph mds
  systemd:
    enabled: yes
    name: ceph-mds@{{ inventory_hostname_short }}
    state: started
  when: '"mds" in ceph_roles'

- name: Run all notified handlers
  meta: flush_handlers
