# SPDX-License-Identifier: Apache-2.0
---
- name: Set facts from variables for cross host queries
  ansible.builtin.set_fact:
    cacheable: true
    ceph_fsid: "{{ ceph_fsid }}"
    ceph_roles: "{{ ceph_roles }}"

- name: Set facts ceph_ip_address from variables if exists
  ansible.builtin.set_fact:
    cacheable: true
    ceph_ip_address: "{{ ceph_ip_address }}"
  when: "ceph_ip_address is defined"

- name: Install debian repository
  ansible.builtin.import_tasks: repo_deb.yml
  when: 'ansible_distribution in ("Ubuntu", "Debian")'

- name: Install centos repository
  ansible.builtin.import_tasks: repo_dnf.yml
  when: 'ansible_distribution == "CentOS"'

- name: Force handler execution
  ansible.builtin.meta: flush_handlers

- name: Install packages
  ansible.builtin.import_tasks: packages.yml

- name: Create cluster keys
  ansible.builtin.import_tasks: create_keys.yml
  when: "ceph_fsid is defined and lookup('template', 'ceph.monitors.names.j2') | from_yaml | sort | first == inventory_hostname"

- name: Force handler execution
  ansible.builtin.meta: flush_handlers
  when: "ceph_fsid is defined"

- name: Deploy cluster keys
  ansible.builtin.import_tasks: deploy_keys.yml
  when: "ceph_fsid is defined"

- name: Force handler execution
  ansible.builtin.meta: flush_handlers
  when: "ceph_fsid is defined"

- name: Configure ceph mon
  ansible.builtin.import_tasks: mon.yml
  when: "ceph_fsid is defined"

- name: Force handler execution
  ansible.builtin.meta: flush_handlers
  when: "ceph_fsid is defined"

- name: Configure ceph osd
  ansible.builtin.import_tasks: osd.yml
  when: "ceph_fsid is defined"

- name: Configure ceph mgr
  ansible.builtin.import_tasks: mgr.yml
  when: "ceph_fsid is defined"

- name: Configure ceph mds
  ansible.builtin.import_tasks: mds.yml
  when: "ceph_fsid is defined"

- name: Configure ceph rgw
  ansible.builtin.import_tasks: rgw.yml
  when: "ceph_fsid is defined"

- name: Configure ceph rbd-mirror
  ansible.builtin.import_tasks: rdb_mirror.yml
  when: "ceph_fsid is defined"
