---
ceph_release: 'squid'
ceph_roles: []
ceph_fsid: ''
ceph_keyrings: ['admin']
ceph_network_public: ''
ceph_network_private: ''
ceph_rbd_cache: '128Mi'
ceph_rbd_cache_max: '96Mi'
ceph_rbd_cache_target: '64Mi'
ceph_disks: []
