---
- name: Set client listen address
  shell:
    cmd: "incus --force-local config set core.https_address {{ incus_ip_address }}"
  when: '(install_deb.changed or install_rpm.changed) and ("standalone" in incus_roles or ("cluster" in incus_roles and incus_servers[0] == inventory_hostname))'

- name: Set cluster listen address
  shell:
    cmd: "incus --force-local config set cluster.https_address {{ incus_ip_address }}"
  when: '(install_deb.changed or install_rpm.changed) and "cluster" in incus_roles and incus_servers[0] == inventory_hostname'

- name: Set OVN NorthBound database
  shell:
    cmd: "incus --force-local config set network.ovn.northbound_connection={{ incus_ovn_northbound }} network.ovn.client_cert=\"{{ lookup('file', 'data/ovn/'+ovn_name+'/'+inventory_hostname+'.crt') }}\" network.ovn.client_key=\"{{ lookup('file', 'data/ovn/'+ovn_name+'/'+inventory_hostname+'.key') }}\" network.ovn.ca_cert=\"{{ lookup('file', 'data/ovn/'+ovn_name+'/ca.crt') }}\""
  notify: Restart Incus
  when: '(install_deb.changed or install_rpm.changed) and incus_ovn_northbound and ("standalone" in incus_roles or ("cluster" in incus_roles and incus_servers[0] == inventory_hostname))'
