---
- name: Add networks
  shell:
    cmd: "incus network create {{ item.key }} --type={{ item.value.type }}{% for k in item.value.local_config | default([]) %} {{ k }}={{ item.value.local_config[k] }}{% endfor %}{% for k in item.value.config | default([]) %} {{ k }}={{ item.value.config[k] }}{% endfor %}"
  loop: "{{ incus_init['network'] | dict2items }}"
  when: '(install_deb.changed or install_rpm.changed) and ("standalone" in incus_roles or ("cluster" in incus_roles and incus_servers[0] == inventory_hostname))'

- name: Set network description
  shell:
    cmd: "incus network set --property {{ item.key }} description=\"{{ item.value.description }}\""
  loop: "{{ incus_init['network'] | dict2items }}"
  when: '(install_deb.changed or install_rpm.changed) and ("standalone" in incus_roles or ("cluster" in incus_roles and incus_servers[0] == inventory_hostname)) and item.value.description | default(None)'

- name: Add network to default profile
  shell:
    cmd: "incus profile device add default eth0 nic network={{ item }} name=eth0"
  loop: "{{ incus_init['network'] | dict2items | json_query('[?value.default].key') }}"
  when: '(install_deb.changed or install_rpm.changed) and ("standalone" in incus_roles or ("cluster" in incus_roles and incus_servers[0] == inventory_hostname))'
