---
- name: Add storage pools
  shell:
    cmd: "incus storage create {{ item.key }} {{ item.value.driver }}{% for k in item.value.local_config | default([]) %} {{ k }}={{ item.value.local_config[k] }}{% endfor %}{% for k in item.value.config | default([]) %} {{ k }}={{ item.value.config[k] }}{% endfor %}"
  loop: "{{ incus_init['storage'] | dict2items }}"
  when: '(install_deb.changed or install_rpm.changed) and ("standalone" in incus_roles or ("cluster" in incus_roles and incus_servers[0] == inventory_hostname))'

- name: Set storage pool description
  shell:
    cmd: "incus storage set --property {{ item.key }} description=\"{{ item.value.description }}\""
  loop: "{{ incus_init['storage'] | dict2items }}"
  when: '(install_deb.changed or install_rpm.changed) and ("standalone" in incus_roles or ("cluster" in incus_roles and incus_servers[0] == inventory_hostname)) and item.value.description | default(None)'

- name: Add storage pool to default profile
  shell:
    cmd: "incus profile device add default root disk path=/ pool={{ item }}"
  loop: "{{ incus_init['storage'] | dict2items | json_query('[?value.default].key') }}"
  when: '(install_deb.changed or install_rpm.changed) and ("standalone" in incus_roles or ("cluster" in incus_roles and incus_servers[0] == inventory_hostname))'
